#on:
#  pull_request:
#    types:
#      - opened
#    branches:
#      - 'main'

on:
  push:
    branches:
      - 'ga-test'

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "JSON_FILE=sample.json" >> $GITHUB_ENV
      - name: set current sprint id
        run: |
          echo "${{ secrets.TEST_EMAIL }}:${{ secrets.TEST_TOKEN }}"
          echo "SPRINT_ID=$(curl --request GET \
          --url 'https://gist.githubusercontent.com/KazumasaYasui/c7f0cd736d8649604a21961a953ad33e/raw/b040478b83ac5bb44e9c1506bb4bb4c51c7fff88/sample1.json' \
          --header 'Accept: application/json' | jq '.values[].id')" >> $GITHUB_ENV
      - name: set base json file
        run: |
          echo ${{ env.SPRINT_ID }}
          curl --request GET \
          --url "https://gist.githubusercontent.com/KazumasaYasui/032fa1b6f1898934950f9fa936b91fa3/raw/c425119d00ad33bc6dc0eeb65726e9dbab5d46ee/sample2.json" \
          --header 'Accept: application/json' | jq -r '.issues[]' > ${{ env.JSON_FILE }}
      - name: set target jira issue keys
        run: |
          TMP_KEY=$(cat ${{ env.JSON_FILE }} | jq -r '. | select(.fields.issuetype.name == "サブタスク" and (.fields.status.name == "staging検証完了")) | .fields.parent.key' | tr '\n' ' ')
          echo $TMP_KEY
          echo "ISSUE_KEY=$TMP_KEY" >> $GITHUB_ENV
      - name: set release category ids
        run: |
          issue_keys=(`echo ${{ env.ISSUE_KEY }}`)
          release_category_ids=()
          echo ${#issue_keys[@]}
          for key in ${issue_keys[@]}; do
          echo $key
          echo $(cat ${{ env.JSON_FILE }} | jq -r ". | select( .key == \"$key\" ) | .fields.customfield_10642.id")
          echo "==="
          done
          for key in ${issue_keys[@]}; do
          release_category_ids+=(`cat ${{ env.JSON_FILE }} | jq -r ". | select( .key == \"$key\" ) | .fields.customfield_10642.id"`)
          done
          echo ${release_category_ids[@]}
          echo "RELEASE_CATEGORY_IDS=${release_category_ids[@]}" >> $GITHUB_ENV
      - name: set release note flag
        run: |
          echo ${{ env.RELEASE_CATEGORY_IDS }}[@]
          if printf '%s\n' "${{ env.RELEASE_CATEGORY_IDS }}[@]" | grep -Eq "10221|10222|10223|10224|10229"; then
            echo "RELEASE_NOTE=TRUE" >> $GITHUB_ENV
          else
            echo "RELEASE_NOTE=FALSE" >> $GITHUB_ENV
          fi
      - name: create jira issue for release note
        if: startsWith(env.RELEASE_NOTE, 'TRUE')
        run: |
          echo ${{ env.RELEASE_NOTE }}
          echo "!!!hogehoge!!!"
          echo ''"${{ env.CURRENT_DATETIME }}"''
